# Generated by Django 5.0.7 on 2024-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_about_me", models.TextField()),
                ("title", models.CharField(max_length=60)),
                ("description_1", models.TextField()),
                ("birth_date", models.DateField()),
                ("age", models.IntegerField()),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("freelance", models.TextField()),
            ],
        ),
    ]
